# Generated by Django 2.1.7 on 2019-02-14 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='US-en', max_length=5, verbose_name='Language')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Picture')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media_channel.Channel', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_channel.Channel', verbose_name='channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Upload File')),
                ('meta_data', models.CharField(blank=True, max_length=100, verbose_name='Meta data')),
                ('rating_no', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rate')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_channel.Channel', verbose_name='channel')),
            ],
        ),
        migrations.CreateModel(
            name='HeadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Active'), ('p', 'Passive')], default='a', max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_channel.HeadGroup', verbose_name='Group'),
        ),
    ]
